sudo: required
services:
  - docker
before_install:
  - gem install bundler
  - docker build -t geekhitesh/react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true geekhitesh/react-frontend  npm run test